### ISSUE TITLE
Descrição de fluxo principal incorreto para caso de uso E4 - Adicionar Professor

### ISSUE THREAD

**Issue by henriquevital00** [GabrielBueno200/SoftwareTestingProject#30]
O fluxo principal do caso de uso E4 - Adicionar Professor, especificado no documento [AOO_FPIJ_Especificacao_de_Requisitos_SRS.doc](https://github.com/GabrielBueno200/SoftwareTestingProject/blob/doc/documentos/AOO_FPIJ_Especificacao_de_Requisitos_SRS.doc) foi descrito de maneira incorreta ao especificar uma condicional (se, senão) na sua descrição. Este erro na especificação do caso de uso inviabiliza a criação do seu teste, pois dificulta a compreensão dos cenários do mesmo ao dividir o fluxo principal em dois.

Severidade: Média.

![caso de uso adicionar professor](https://user-images.githubusercontent.com/48650626/202865196-f9eefe97-8238-4fee-b431-89651787896b.png)

**Comment by GabrielBueno200** [comment]
Esta issue foi resolvida com a correção do formulário do caso de uso E4, incluído na [Wiki](https://github.com/GabrielBueno200/SoftwareTestingProject/wiki/Casos-de-Uso) deste repositório. A condição especificada no Fluxo Principal foi substituída por um fluxo alternativo para o caso do professor possuir registro de aluno.
