### ISSUE TITLE
Descrição incorreta do fluxo alternativo 3.a. para caso de uso E10 - Atualizar Entidade

### ISSUE THREAD

**Issue by henriquevital00** [GabrielBueno200/SoftwareTestingProject#33]
O fluxo alternativo do caso de uso E10 - Atualizar Entidade, especificado no documento [AOO_FPIJ_Especificacao_de_Requisitos_SRS.doc](https://github.com/GabrielBueno200/SoftwareTestingProject/blob/doc/documentos/AOO_FPIJ_Especificacao_de_Requisitos_SRS.doc) foi descrito de maneira incorreta ao não especificar um passo de retorno para o fluxo principal, o que pode causar mais de uma interpretação.

Severidade: Baixa.

![fluxo alternativo caso de uso e10](https://user-images.githubusercontent.com/48650626/202911460-6f2b2c20-96b3-4e1e-a577-81ac1fc0b3bb.png)

**Comment by GabrielBueno200** [comment]
Esta issue foi resolvida com a correção do formulário do caso de uso E9, incluído na [Wiki](https://github.com/GabrielBueno200/SoftwareTestingProject/wiki/Casos-de-Uso) deste repositório. O Fluxo Alternativo 3.a foi corrigido.
